### PR TITLE
Add repo-mapping support for Julia language

### LINKED ISSUE #1975: Add repo-mapping support for Julia language
### Issue

I've found the `julia-syntax.scm` file for Julia, which can be used to implement repo-mapping support:  https://github.com/JuliaLang/julia/blob/master/src/julia-syntax.scm

Julia already has linting support in Aider, making it a [good candidate](https://aider.chat/docs/languages.html#how-to-add-support-for-another-language) for adding repo-map support.

Can we integrate this to add repo-mapping support for Julia in Aider?

### Version and model info

_No response_

### PR DESCRIPTION
**Pull request by younes-io**
Fixes #1975

Add repo-mapping support for Julia language

### CODE REVIEW

**Comment by younes-io** [comment]
@fry69 do you think someone can review this PR?

**Comment by paul-gauthier** [comment]
Thanks for your interest in aider and for making this PR.

Unfortunately there are a bunch of problems with this PR, so it's unlikely that I can merge it.

Where did you get the Julia scm file? Perhaps I can incorporate it at some point.

**Comment by younes-io** [comment]
@paul-gauthier : I got it from the official repo: https://github.com/JuliaLang/julia/blob/master/src/julia-syntax.scm
I have mentioned it in https://github.com/Aider-AI/aider/issues/1975

**Comment by paul-gauthier** [comment]
Sorry, the scm file you link from JuliaLang looks nothing like the scm file in this PR?

**Comment by younes-io** [comment]
@paul-gauthier sorry, I didn't pay attention to that! I have just put the contents of JuliaLang's scm file.

**Comment by paul-gauthier** [comment]
Sorry, the file you had was better. I was trying to figure out where you got that file.

Again, this PR has multiple problems so I can't merge it. But if you can tell me where you got the SCM file that was here before that would help me add Julia support later.

**Comment by younes-io** [comment]
> Sorry, the file you had was better. I was trying to figure out where you got that file.
> 
> Again, this PR has multiple problems so I can't merge it. But if you can tell me where you got the SCM file that was here before that would help me add Julia support later.

ah, the old one, I generated using aider and an LLM (don't remember exactly, which one)

**Comment by younes-io** [comment]
I did a git rebase https://github.com/younes-io/aider/blob/add-julia-repo-mapping/aider/queries/tree-sitter-julia-tags.scm

**Comment by paul-gauthier** [comment]
So the trick is we need a correct and accurate tags.scm file. I'm not sure I can ship one with no provenance.

**Pull request closed without merging**
