### PR TITLE
Add support for Gemini API key in command line and config file

### PR DESCRIPTION
**Pull request by paulmaunders**
This allows users to use Gemini models by passing their API key via the `--gemini-api-key` command line argument, or by setting it in the `.aider.conf.yml`

### CODE REVIEW

**Comment by paul-gauthier** [comment]
Why not use .env?

**Comment by paulmaunders** [comment]
The command line option is useful for quick testing without modifying files and enables support for .aider.conf.yml

Gemini seems to be offering some of highest performing _free_ APIs at the moment, so I thought it should be as easy to use up as Anthropic and OpenAI.  Unless `.aider.conf.yml` is being deprecated?

**Comment by paul-gauthier** [comment]
It's just a slippery slope. There are dozens of `---xxx-api-key` switches we could add.

**Comment by paul-gauthier** [comment]
I just added `--set-env FOO=bar`, so now you can do this in the yml file:

```
set-env: GEMINI_API_KEY=<your-key>
```

**Comment by paulmaunders** [comment]
Great, thank you!

**Comment by paul-gauthier** [comment]
There's also `--api-key gemini=<key>` now too.

**Pull request closed without merging**
