### PR TITLE
changed prompt: replace all to replace first

### PR DESCRIPTION
**Pull request by mw3155**
i think this prompt is wrong. 
SEARCH/REPLACE blocks will only replace the first occurrence not all.

edit: fixed typo in sentence after first change

### CODE REVIEW

**Comment by alexanderkjeldaas** [comment]
I have no idea what is better, but if I was the AI, with this change I would not have to consider the rest of the file after the first match, so it should be less work on average.

**Comment by paul-gauthier** [comment]
Thanks for putting together this PR.

I have benchmarked both versions, and the current way aider handles this produces superior results.

**Comment by mw3155** [comment]
@paul-gauthier thanks for the reply. thats very interesting. 
do you have any idea why it would produce superior results even though it looks like the prompt could be misleading?

you can close this issue.

**Comment by paul-gauthier** [comment]
Sorry, what makes you think it only replaces 1 occurrence?

**Comment by mw3155** [comment]
i tried it out with gpt4o. and then i looked at the code. maybe i misunderstand something.
i was looking at editblock_coder.py
the function do_replace calls replace_most_similar_chunk which calls ... until perfect_replace, which replaces the first occurance of the search block, right?

**Comment by paul-gauthier** [comment]
Ok, good point. I've fixed the prompt and added test coverage so this is more clearly documented in the codebase.

The implementation that was in the repo was the one which benchmarked better.

Thanks for bringing this to my attention!

**Pull request closed without merging**
