### PR TITLE
Some more open source models

### PR DESCRIPTION
**Pull request by itlackey**
- Dolphin Mixtral
- Mistral Nemo 12b
- Qwen 2.5 Coder 7b instruct fp16
- Qwen 2.5 32b q2_k
- Deepseek Coder v2 16b lite instruct q4_k_m
- Starcoder2 15b instruct v0.1 q8_0
- Codegeex4 9b all q6_k
- Updated codestral to newer version of aider

### CODE REVIEW

**Comment by Kreijstal** [comment]
@itlackey it has conflicts

**Comment by itlackey** [comment]
Sorry this took a while. It should be resolved now.

**Comment by paul-gauthier** [comment]
These benchmarks look like they were done before aider defaulted the `num_ctx` to 8k for Ollama models?

**Comment by itlackey** [comment]
You are probably right. It has sat for a while. We can close this and I can rerun, and submit a new PR. Sorry for the hassle.

**Pull request closed without merging**
