### PR TITLE
fix: Ensure consistent language in coder prompt descriptions

### LINKED ISSUE #1850: Answering in Spanish
### Issue

Is there a reason this would have been answering in spanish?

PS C:\Windows\system32> cd "C:\Users\TC\Desktop\InventoryApp"
PS C:\Users\TC\Desktop\InventoryApp> git init
Initialized empty Git repository in C:/Users/TC/Desktop/InventoryApp/.git/
PS C:\Users\TC\Desktop\InventoryApp> aider --model openrouter/openai/o1-preview --architect --editor-model openrouter/anthropic/claude-3-5-20240620
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Newer aider version v0.58.1 is available.
Run this command to update:

python.exe -m pip install --upgrade --upgrade-strategy only-if-needed aider-chat
Add .aider* to .gitignore (recommended)? (Y)es/(N)o [Yes]: y
Added .aider* to .gitignore
Warning for openrouter/openai/gpt-4o-mini: Unknown context window size and costs, using sane defaults.
Did you mean one of these?
- openrouter/openai/gpt-4
- openrouter/openai/gpt-4o
- openrouter/openai/o1-mini
For more info, see: https://aider.chat/docs/llms/warnings.html
You can skip this check with --no-show-model-warnings

Proceed anyway? (Y)es/(N)o [Yes]: y
Warning: Streaming is not supported by openrouter/openai/o1-preview. Disabling streaming.
Aider v0.58.1.dev8+g0aaa37f5
Main model: openrouter/openai/o1-preview with architect edit format
Editor model: openrouter/anthropic/claude-3-5-20240620 with editor-diff edit format
Weak model: openrouter/openai/gpt-4o-mini
Git repo: .git with 0 files
Repo-map: using 1024 tokens, auto refresh
Use /help <question> for help, run "aider --help" to see cmd line args
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
architect> create an invenotry tracking, mangement, and counting app designed for hotel managers. create cool and usefu
l features. and ensure the design is futurstic and userfriendly

Para abordar la solicitud de crear una aplicación de seguimiento, gestión y conteo de inventario diseñada para gerentes
de hoteles con características innovadoras y un diseño futurista y fácil de usar, sigue estos pasos:

  1 Diseño de Interfaz de Usuario Futurista:
     • Implementa una interfaz limpia y minimalista con gráficos modernos y animaciones suaves.
     • Utiliza una paleta de colores que refleje un ambiente profesional y futurista, como tonos de azul, gris y blanco.
     • Incorpora iconografía intuitiva y tipografía clara para mejorar la legibilidad.
  2 Funcionalidades Principales:
     • Panel de Control Personalizado:
        • Crea un tablero principal que muestre en tiempo real el estado del inventario, alertas y métricas clave.
        • Permite a los usuarios personalizar widgets y vistas según sus necesidades.
     • Seguimiento de Inventario en Tiempo Real:
        • Desarrolla una función para actualizar automáticamente los niveles de inventario al recibir o consumir
          artículos.
        • Integra lectores de códigos de barras o QR para agilizar el proceso de entrada y salida de productos.
     • Gestión de Múltiples Almacenes:
        • Habilita la gestión de inventario en diferentes ubicaciones dentro del hotel, como cocinas, bares y almacenes
          de limpieza.
        • Permite transferencias de stock entre ubicaciones con registro automático de movimientos.
  3 Características Innovadoras:
     • Análisis Predictivo:
        • Implementa algoritmos que analicen patrones de consumo y proporcionen previsiones sobre futuras necesidades de
          stock.
        • Genera alertas proactivas para reordenar productos antes de que se agoten.
     • Integración con Proveedores:
        • Crea una función que permita realizar pedidos automáticamente a proveedores cuando los niveles de inventario
          alcancen umbrales predefinidos.
        • Facilita la comunicación y seguimiento de órdenes de compra desde la aplicación.
     • Registro de Auditorías:
        • Mantén un historial detallado de todas las transacciones y cambios en el inventario para fines de seguimiento
          y auditoría.
        • Permite exportar informes en diferentes formatos (PDF, Excel).
  4 Mejoras en la Experiencia de Usuario:
     • Navegación Intuitiva:
        • Diseña menús y secciones claramente etiquetados para facilitar el acceso a diferentes funciones.
        • Implementa una función de búsqueda avanzada con filtros específicos.
     • Soporte Multilingüe:
        • Añade soporte para múltiples idiomas para acomodar a usuarios de diversas nacionalidades.
     • Notificaciones Inteligentes:
        • Configura notificaciones push y alertas in-app para eventos críticos como bajas existencias o discrepancias en
          el conteo.
     • Modo Oscuro/Claro:
        • Ofrece opciones de visualización en modo oscuro y claro para reducir la fatiga visual y adaptarse a las
          preferencias del usuario.
  5 Optimización y Futurización:
     • Tecnologías de Vanguardia:
        • Considera el uso de inteligencia artificial y aprendizaje automático para mejorar la precisión en el conteo y
          gestión de inventario.
        • Explora la incorporación de realidad aumentada para visualizar el inventario y su ubicación física.
     • Aplicación Móvil y Web Responsive:
        • Asegura que la aplicación sea totalmente responsiva y accesible desde dispositivos móviles, tabletas y
          computadoras.
        • Optimiza el rendimiento para garantizar tiempos de carga rápidos y una experiencia fluida.
  6 Seguridad y Cumplimiento:
     • Autenticación y Autorización Seguras:
        • Implementa autenticación de dos factores y controles de acceso basados en roles para proteger los datos
          sensibles.
     • Encriptación de Datos:
        • Asegura que todos los datos almacenados y transmitidos estén encriptados siguiendo los estándares de
          seguridad.
     • Cumplimiento Normativo:
        • Verifica que la aplicación cumpla con las regulaciones locales e internacionales pertinentes, como GDPR si
          aplica.
  7 Integraciones Adicionales:
     • Compatibilidad con Otros Sistemas:
        • Facilita la integración con sistemas existentes de gestión hotelera (PMS), puntos de venta (POS) y
          contabilidad.
        • Proporciona APIs y webhooks para extender la funcionalidad y permitir integraciones personalizadas.
  8 Pruebas y Depuración:
     • Realiza Pruebas Exhaustivas:
        • Ejecuta pruebas unitarias y de integración para garantizar la fiabilidad de las nuevas funciones.
        • Recopila feedback de usuarios beta para identificar y corregir problemas de usabilidad.
  9 Documentación y Soporte:
     • Actualiza la Documentación Técnica:
        • Detalla los cambios realizados y proporciona instrucciones claras para la implementación.
     • Guías de Usuario y Tutoriales:
        • Crea recursos educativos para ayudar a los gerentes a aprovechar al máximo las nuevas funciones.

Por favor, implementa estas mejoras asegurándote de que cada nueva característica se integre de manera cohesiva con el
código existente y se mantenga la alta calidad y eficiencia de la aplicación.

Tokens: 207 sent, 2.5k received. Cost: $0.15 message, $0.15 session.
Edit the files? (Y)es/(N)o [Yes]:

### Version and model info

S C:\Windows\system32> cd "C:\Users\TC\Desktop\InventoryApp"
PS C:\Users\TC\Desktop\InventoryApp> git init
Initialized empty Git repository in C:/Users/TC/Desktop/InventoryApp/.git/
PS C:\Users\TC\Desktop\InventoryApp> aider --model openrouter/openai/o1-preview --architect --editor-model openrouter/anthropic/claude-3-5-20240620
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Newer aider version v0.58.1 is available.
Run this command to update:

python.exe -m pip install --upgrade --upgrade-strategy only-if-needed aider-chat
Add .aider* to .gitignore (recommended)? (Y)es/(N)o [Yes]: y
Added .aider* to .gitignore
Warning for openrouter/openai/gpt-4o-mini: Unknown context window size and costs, using sane defaults.
Did you mean one of these?
- openrouter/openai/gpt-4
- openrouter/openai/gpt-4o
- openrouter/openai/o1-mini
For more info, see: https://aider.chat/docs/llms/warnings.html
You can skip this check with --no-show-model-warnings

Proceed anyway? (Y)es/(N)o [Yes]: y
Warning: Streaming is not supported by openrouter/openai/o1-preview. Disabling streaming.
Aider v0.58.1.dev8+g0aaa37f5
Main model: openrouter/openai/o1-preview with architect edit format
Editor model: openrouter/anthropic/claude-3-5-20240620 with editor-diff edit format
Weak model: openrouter/openai/gpt-4o-mini
Git repo: .git with 0 files
Repo-map: using 1024 tokens, auto refresh
Use /help <question> for help, run "aider --help" to see cmd line args

### PR DESCRIPTION
**Pull request by fry69**
fix #1850

Thanks to @businistry for reporting and @jorgecolonconsulting for digging into this and providing the fix!

### CODE REVIEW

**Comment by jorgecolonconsulting** [comment]
you're welcome!

**Comment by paul-gauthier** [comment]
Why do we think this rephrasing "works better" in general? It seems quite similar.

**Comment by fry69** [comment]
> Why do we think this rephrasing "works better" in general? It seems quite similar.

Mystery of LLMs I guess? There is a slightly different meaning or instruction logic the new wording, I think.

**Comment by jorgecolonconsulting** [comment]
> Why do we think this rephrasing "works better" in general? It seems quite similar.

Not so much “think” as in actually tested against a couple of different models. The biggest thing it fixes is where the default strong model (gpt-4o) that Aider uses responds in Spanish as many have reported here. That leaves a bit of a bad first impression when you’re expecting Aider to respond in your expected language.

LLMs are weird in that slight changes in a prompt can have dramatic changes in behavior for unknown reasons. Even if they are essentially saying the same thing. I’m sure you’ve experienced that yourself.

Have a look here where I was able to reproduce the problem and where this prompt did better: https://github.com/Aider-AI/aider/issues/1850#issuecomment-2392070378

**Comment by jorgecolonconsulting** [comment]
A thorough test across many models can make sure that prompt did better. We could even ask the issue reporters that experienced responses in Spanish what their chat history and incorporate those into the tests.

**Pull request closed without merging**
