### PR TITLE
Add dart support

### PR DESCRIPTION
**Pull request by malkoG**

### CODE REVIEW

**Comment by paul-gauthier** [comment]
Thanks, where did you source this scm file?

**Comment by malkoG** [comment]
I sourced from here https://github.com/UserNobody14/tree-sitter-dart/blob/master/queries/tags.scm  👀

**Comment by albemala** [comment]
I’d be interested in having dart and flutter supported in Aider. @paul-gauthier is there anything I can do to help having this PR merged?

**Comment by albemala** [comment]
No worries at all @paul-gauthier , thank you for your great work on Aider! As a side note, will this change be enough to support mapping dart and flutter projects?

**Comment by paul-gauthier** [comment]
It should. You can do `aider --show-repo-map` in your repo and see.

**Comment by albemala** [comment]
awesome, thank you

**Comment by paul-gauthier** [comment]
@malkoG did you test this PR before submitting it?

**Comment by malkoG** [comment]
Sorry, i didn't. I only tried on treesitter-dart repository.

**Comment by nkeilar** [comment]
We tested and its just outputting a list of dart filenames in the repomap... should there be more introspection going on than that... the filenames alone don't provide much context really... Maybe another library is needed as well? @malkoG

**Comment by malkoG** [comment]
Okay, I'll try it

**Comment by paul-gauthier** [comment]
This pr did not add support for dart. It has been rolled back in the main branch.

**Pull request merged**
